name: Deploy to dracor.org
on:
  workflow_dispatch:
    inputs:
      server:
        description: Server
        type: choice
        required: true
        options:
          - "staging.dracor.org"
          - "dracor.org"

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      # adjust config
      - run: sed -i -e "s|dracor-org\.github\.io/dracor-summit|summit.${{ inputs.server }}|" _config.yml
      - run: sed -i -e "s|dracor-org\.github\.io/dracor-summit|summit.${{ inputs.server }}|" _includes/head.html
      - run: cat _config.yml

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@44a6e6beabd48582f863aeeb6cb2151cc1716697 # v1.0.13
        with:
          source: ./
          destination: ./_site

      # adjust remaining /dracor-summit occurrences
      - name: Fix URL paths
        run: |
          cp -rv _site _sitex
          for f in $(grep -l /dracor-summit -r _sitex); do
            sed -i -e "s|/dracor-summit/|/|g" $f
          done

      - uses: webfactory/ssh-agent@e83874834305fe9a4a2997156cb26c5de65a8555 # v0.10.0
        with:
          ssh-private-key: ${{ secrets.DRACOR_ORG_DEPLOY_KEY }}

      - name: Deploy to ${{ inputs.server }}
        run: |
          rsync -rlvz --delete \
            -e 'ssh -o StrictHostKeyChecking=no' \
            ./_sitex/ \
            ${{ secrets.DRACOR_ORG_DEPLOY_USER }}@${{ inputs.server }}:/var/www/summit/
